const EVENT={id:"converge-01",name:"Convergência 01",city:"Florianópolis",hint:"Campeche · Rio Tavares · Morro das Pedras",day:"Um dia · 10h–22h",liveUntil:"Live oficial até 15h · convivência não transmite"};
const WORKER="https://akasha.yanfili-simon.workers.dev";
const LK_URL="wss://akashahub-vlya29kl.livekit.cloud";
const CEO_EMAILS=["yanfili.simon@gmail.com","plmacramo@gmail.com","sendatantrica@gmail.com","opatricksimon@gmail.com"];
const CEO_UIDS=["1GO7dRdFUFg2NwYwzOwjvtWfpAS2"];
const LS="converge.mini.v2";
const TICKETS={founder:{label:"Presencial Fundador",kind:"presencial",ents:["presencial","live","replay","kit"]},presencial:{label:"Presencial",kind:"presencial",ents:["presencial","live","replay","kit"]},online:{label:"Online · live + 90 dias",kind:"online",ents:["live","replay"]}};
const MISSIONS=[{id:"perfil",title:"Perfil 100%",xp:20,hint:"Nome, o que faz, o que busca, o que compartilha."},{id:"video",title:"Vídeo Quem Sou",xp:20,hint:"2–3 min. Cole a URL."},{id:"pre",title:"Pré-encontro",xp:20,hint:"Ao vivo ou replay + um comentário."},{id:"conexao",title:"Uma conexão",xp:20,hint:"Vídeo 30–60s com outra pessoa — URL."},{id:"momento",title:"Um momento",xp:20,hint:"Registro 15–30s. URL."}];
const QUOTA={refeicao:1,segunda:1,lanche:2,bebida:3};
const AGENDA=[["10:00","Chegada · kit · pulseirinha · lanche"],["11:00","Abertura"],["11:15","Preparação corporal"],["11:35","Quem está aqui · 60s"],["12:35","Fascinação e presença"],["13:35","Magnetismo e comunicação"],["14:15","Conexões em duplas"],["15:00","Refeição · live oficial encerra"],["16:00","Piscina e convivência · sem transmissão"],["18:30","Segunda oferta de comida"],["21:30","Despedida"]];
firebase.initializeApp({apiKey:"AIzaSyAQXJDGfsd7RgcYKm9wfuh6nOth7dWo-v4",authDomain:"hub-akasha.firebaseapp.com",projectId:"hub-akasha",storageBucket:"hub-akasha.firebasestorage.app",messagingSenderId:"370851875474",appId:"1:370851875474:web:29b1ba3a76b0fed7d9344b"});
const auth=firebase.auth();const db=firebase.firestore();auth.setPersistence(firebase.auth.Auth.Persistence.LOCAL);
function load(){try{return JSON.parse(localStorage.getItem(LS))||{users:{},access:{},tx:[],posts:[],cons:[],logs:[]}}catch(e){return{users:{},access:{},tx:[],posts:[],cons:[],logs:[]}}}
function save(){localStorage.setItem(LS,JSON.stringify(C))}let C=load();let me=null,route="boot",cloud="checking",draft={};let lkRoom=null;
function isCeo(u){if(!u)return false;return CEO_UIDS.includes(u.uid)||CEO_EMAILS.includes((u.email||"").toLowerCase())}
function toast(t){const e=document.createElement("div");e.className="toast";e.textContent=t;document.body.appendChild(e);setTimeout(()=>e.remove(),2200)}
function go(r){route=r;render()}function iso(){return new Date().toISOString()}function esc(s){return String(s||"").replace(/[&<>"']/g,c=>({"&":"&","<":"<",">":">","\"":""","'":"&#39;"}[c]))}
function first(n){return(n||"Você").split(" ")[0]}
async function tryCloud(fn){try{await fn();cloud="ok";return true}catch(err){if(String(err.code||err).includes("permission"))cloud="rules";else cloud="err";return false}}
function user(uid){return C.users[uid]}function mine(){return me&&C.users[me.uid]}function acc(uid){return C.access[uid]||null}
function xp(uid){return(C.tx||[]).filter(t=>t.userId===uid).reduce((s,t)=>s+t.amount,0)}
function has(uid,id){return(C.tx||[]).some(t=>t.userId===uid&&t.action===id)}
function isTop(uid){return MISSIONS.every(m=>has(uid,m.id))}
function grant(uid,action,amount){if(has(uid,action))return false;C.tx.push({id:uid+"_"+action,userId:uid,action,amount,at:iso()});save();tryCloud(()=>db.collection("legado_points").doc(uid+"_"+action).set({userId:uid,eventId:EVENT.id,action,amount,at:iso()}));return true}
function persistUser(u){C.users[u.uid]=Object.assign(C.users[u.uid]||{},u);save();tryCloud(()=>db.collection("legado_users").doc(u.uid).set(u,{merge:true}))}
function persistAccess(uid,a){C.access[uid]=Object.assign(C.access[uid]||{},a,{uid});save();tryCloud(()=>db.collection("legado_access").doc(uid).set(C.access[uid],{merge:true}))}
function log(kind,detail){C.logs.unshift({at:iso(),kind,detail,actor:me&&me.email});C.logs=C.logs.slice(0,60);save()}
function qrToken(uid){return btoa(uid+"|"+EVENT.id+"|"+Math.floor(Date.now()/30000)).replace(/=+$/,"").slice(0,28)}
function ensure(fb){const old=C.users[fb.uid]||{};persistUser({uid:fb.uid,email:fb.email||"",name:old.name||fb.displayName||"",photo:old.photo||fb.photoURL||"",createdAt:old.createdAt||iso(),lastLogin:iso(),role:isCeo(fb)?"ADMIN":old.role||"PARTICIPANTE",onboardingDone:!!old.onboardingDone,public:old.public||{},video:old.video||"",conexao:old.conexao||"",momento:old.momento||"",preComment:old.preComment||""});if(isCeo(fb)&&!acc(fb.uid))persistAccess(fb.uid,{status:"active",ticket:"founder",ents:TICKETS.founder.ents,at:iso()});const byEmail=Object.values(C.access).find(a=>a.email&&a.email.toLowerCase()===(fb.email||"").toLowerCase()&&a.status==="active");if(byEmail&&!acc(fb.uid))persistAccess(fb.uid,{status:"active",ticket:byEmail.ticket,ents:byEmail.ents,email:fb.email,at:iso()})}
function entitled(){if(!me)return false;if(isCeo(me))return true;const a=acc(me.uid);return a&&a.status==="active"}
auth.onAuthStateChanged(async(u)=>{me=u?{uid:u.uid,email:u.email,displayName:u.displayName,photoURL:u.photoURL}:null;if(!me){route="login";render();return}ensure(me);await tryCloud(async()=>{const snap=await db.collection("legado_users").doc(me.uid).get();if(snap.exists)C.users[me.uid]=Object.assign(C.users[me.uid]||{},snap.data());const a=await db.collection("legado_access").doc(me.uid).get();if(a.exists)C.access[me.uid]=Object.assign(C.access[me.uid]||{},a.data());if(isCeo(me)){(await db.collection("legado_users").get()).forEach(d=>{C.users[d.id]=Object.assign(C.users[d.id]||{},d.data())});(await db.collection("legado_access").get()).forEach(d=>{C.access[d.id]=Object.assign(C.access[d.id]||{},d.data())})}save()});ensure(me);if(!entitled()){route="pending";render();return}if(!mine().onboardingDone){route="onboard";render();return}if(["boot","login","pending","onboard"].includes(route))route="home";render()});
async function loginGoogle(){const p=new firebase.auth.GoogleAuthProvider();p.setCustomParameters({prompt:"select_account"});try{await auth.signInWithPopup(p)}catch(e){if(e.code==="auth/popup-blocked"||e.code==="auth/cancelled-popup-request"){await auth.signInWithRedirect(p);return}toast(e.message||"Falha no Google")}}
function logout(){auth.signOut()}
function viewLogin(){return `<div class="gate"><div class="k">${EVENT.name} · Mini</div><h1>Um dia. Presença. Gente.</h1><p class="q">${EVENT.city}. ${EVENT.hint}. Local exato depois da pré-venda.</p><p class="q">Presencial R$497 · Online live + 90 dias · 6 fundadores já reservados.</p><button class="btn" onclick="loginGoogle()">Continuar com Google</button><p class="m" style="text-align:center;margin-top:16px">O evento começa no celular. Pulseirinha no dia.</p></div>`}
function viewPending(){const u=mine()||{};return `<div class="gate"><div class="k">Ingresso</div><h1>Conta criada.<br>Aguardando liberação.</h1><p class="q">${esc(u.email)}</p><div class="card"><div class="m">UID</div><div style="word-break:break-all;font-size:12px">${u.uid}</div><p class="q">Quem pagou ou é fundador é liberado no painel.</p></div><button class="btn btn2" onclick="logout()">Sair</button>${cloud==="rules"?`<div class="banner">Cole as rules legado_* no Firestore.</div>`:""}</div>`}
function viewOnboard(){const u=mine();draft=Object.assign({name:u.name,does:(u.public||{}).does,seek:(u.public||{}).seek,share:(u.public||{}).share},draft);return `<div class="wrap"><div class="row"><div class="brand">Convergência</div><button class="pill" onclick="logout()">Sair</button></div><div class="k">Missão 1 · Perfil</div><h1>Como você chega.</h1><label>Nome</label><input id="n" value="${esc(draft.name||"")}"><label>O que você faz</label><input id="d" value="${esc(draft.does||"")}"><label>O que você busca neste dia</label><textarea id="s">${esc(draft.seek||"")}</textarea><label>O que você pode compartilhar</label><textarea id="h">${esc(draft.share||"")}</textarea><button class="btn" onclick="saveOnboard()">Entrar no encontro</button></div>`}
function saveOnboard(){const u=mine();u.name=(document.getElementById("n").value||"").trim();u.public={does:document.getElementById("d").value.trim(),seek:document.getElementById("s").value.trim(),share:document.getElementById("h").value.trim()};if(u.name.length<2||!u.public.does||!u.public.seek){toast("Nome, o que faz e o que busca");return}u.onboardingDone=true;persistUser(u);if(grant(u.uid,"perfil",20))toast("+20 · perfil");go("home")}
function ticketOf(uid){const a=acc(uid)||{ticket:"online"};return TICKETS[a.ticket]||TICKETS.online}
function used(uid,item){return(C.cons||[]).filter(c=>c.uid===uid&&c.item===item).length}
function viewHome(){const u=mine();const top=isTop(u.uid);const t=ticketOf(u.uid);const done=MISSIONS.filter(m=>has(u.uid,m.id)).length;return shell(`<div class="k">${EVENT.name} · ${EVENT.city}</div><h1>${first(u.name)}, ${top?"você é Player Top.":"o dia ainda começa no app."}</h1><p class="q">${EVENT.hint}</p><div class="card"><div class="row"><div><div class="m">${t.label}</div><h3>${top?"PLAYER TOP":"Padrão"}</h3></div><span class="pill ${top?"ok":""}">${xp(u.uid)} / 100</span></div><div class="xp"><i style="width:${Math.min(100,xp(u.uid))}%"></i></div><p class="m" style="margin-top:8px">${done}/5 missões · VIP até D-1 23h59</p></div><div class="card"><div class="m">Meu ingresso</div><div class="qr">${qrToken(u.uid)}</div><p class="m">QR da pulseirinha · gira a cada 30s</p>${t.kind==="online"?`<p class="q">Online não tem pulseira física. Live até 15h + replay 90 dias.</p>`:""}</div><div class="card"><h3>Grelha do dia</h3>${AGENDA.map(a=>`<div class="row slot"><span class="m">${a[0]}</span><span class="q">${a[1]}</span></div>`).join("")}<p class="m">${EVENT.liveUntil}</p></div>${cloud==="rules"?`<div class="banner">Rules legado_* ainda não publicadas.</div>`:""}`)}
function viewPlay(){const u=mine();return shell(`<div class="k">Missões · Player Top</div><h1>Cem pontos até a véspera.</h1><p class="q">Completou as cinco: pulseirinha dourada e consumo liberado.</p>${MISSIONS.map(m=>`<div class="card"><div class="row"><h3>${m.title}</h3><span class="pill ${has(u.uid,m.id)?"ok":""}">${has(u.uid,m.id)?"feita":"+"+m.xp}</span></div><p class="q">${m.hint}</p>${m.id==="video"?fieldUrl("video",u.video):""}${m.id==="conexao"?fieldUrl("conexao",u.conexao):""}${m.id==="momento"?fieldUrl("momento",u.momento):""}${m.id==="pre"&&!has(u.uid,"pre")?`<label>Comentário do pré-encontro</label><textarea id="pre">${esc(u.preComment||"")}</textarea><button class="btn" onclick="doPre()">Marcar presença</button>`:""}${m.id==="perfil"&&!has(u.uid,"perfil")?`<button class="btn btn2" onclick="go('onboard')">Completar perfil</button>`:""}</div>`).join("")}`)}
function fieldUrl(key,val){if(has(me.uid,key))return val?`<p class="m">${esc(val)}</p>`:"";return `<label>URL</label><input id="${key}" placeholder="https://" value="${esc(val||"")}"><button class="btn" onclick="saveUrl('${key}')">Enviar</button>`}
function saveUrl(key){const url=(document.getElementById(key).value||"").trim();if(!/^https?:\/\//i.test(url)){toast("Cole uma URL http(s)");return}const u=mine();u[key]=url;persistUser(u);if(grant(u.uid,key,20))toast("+20");render()}
function doPre(){const txt=(document.getElementById("pre").value||"").trim();if(txt.length<8){toast("Escreve o que ficou");return}const u=mine();u.preComment=txt;persistUser(u);if(grant(u.uid,"pre",20))toast("+20 · pré-encontro");render()}
function viewPeople(){const list=Object.values(C.users).filter(u=>u.onboardingDone);return shell(`<div class="k">Participantes</div><h1>Quem está neste piloto.</h1><div class="card"><label>Postar no feed</label><textarea id="post" placeholder="Uma frase."></textarea><button class="btn" onclick="addPost()">Publicar</button></div>${(C.posts||[]).slice(0,12).map(p=>`<div class="card"><strong>${esc(p.name)}</strong><p class="q">${esc(p.text)}</p><p class="m">${p.at.slice(11,16)}</p></div>`).join("")}${list.map(u=>`<div class="card"><div class="person"><div class="av">${u.photo?`<img src="${esc(u.photo)}">`:(u.name||"?")[0]}</div><div><strong>${esc(u.name)}</strong><div class="m">${esc((u.public||{}).does||"")} · ${isTop(u.uid)?"Player Top":ticketOf(u.uid).label}</div></div></div><p class="q">${esc((u.public||{}).seek||"")}</p></div>`).join("")||`<div class="card"><p class="q">Ainda só você neste aparelho.</p></div>`}`)}
function addPost(){const text=(document.getElementById("post").value||"").trim();if(text.length<2)return;C.posts.unshift({name:mine().name,uid:me.uid,text,at:iso()});C.posts=C.posts.slice(0,40);save();render()}
function viewLive(){const t=ticketOf(me.uid);const can=t.ents.includes("live");return shell(`<div class="k">Ao vivo</div><h1>Pré-encontro e práticas.</h1><p class="q">${EVENT.liveUntil}</p><div class="card"><h3>Sala do mentor</h3><p class="q">Uma sala no Mini. LiveKit no Worker.</p>${can?`<button class="btn" onclick="joinMiniLive()">Entrar na sala</button><button class="btn btn2" onclick="leaveMiniLive()">Sair</button>`:`<p class="m">Seu ingresso não inclui ao vivo.</p>`}<div id="lk-grid" class="lk-grid"></div></div><div class="card"><h3>Replay · 90 dias</h3><p class="q">Pré-encontro · Práticas 11h–15h. Piscina não entra para o online.</p></div>`)}
async function joinMiniLive(){if(!window.LivekitClient){toast("LiveKit carregando");return}try{if(lkRoom)await lkRoom.disconnect();const res=await fetch(WORKER,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({identity:me.uid,room:"converge-mentor",name:mine().name,mentor:isCeo(me)})});const data=await res.json();if(!data.token)throw new Error(data.error||"token");lkRoom=new LivekitClient.Room({adaptiveStream:true,dynacast:true});await lkRoom.connect(data.url||LK_URL,data.token);if(isCeo(me)||ticketOf(me.uid).kind==="presencial")await lkRoom.localParticipant.enableCameraAndMicrophone();toast(isCeo(me)?"Mentor no ar":"Assistindo")}catch(e){toast(e.message||"Falha na sala")}}
async function leaveMiniLive(){try{if(lkRoom)await lkRoom.disconnect()}catch(e){}lkRoom=null;toast("Saiu")}
function viewMe(){const u=mine();const top=isTop(u.uid);const t=ticketOf(u.uid);return shell(`<div class="k">Eu</div><div class="person"><div class="av">${u.photo?`<img src="${esc(u.photo)}">`:(u.name||"?")[0]}</div><div><h1>${esc(u.name)}</h1><p class="q">${esc(u.email)}</p></div></div><div class="card">${t.label} · ${top?"PLAYER TOP":"Padrão"} · ${xp(u.uid)} pts</div>${isCeo(me)?`<button class="btn btn3" onclick="go('staff')">Painel staff / mentor</button>`:""}<button class="btn btn2" onclick="logout()">Sair</button>`)}
function viewStaff(){if(!isCeo(me))return viewMe();const users=Object.values(C.users);return shell(`<div class="k">Staff · Mentor</div><h1>Pulseirinha e acesso.</h1><div class="card"><label>E-mail de quem pagou ou é fundador</label><input id="gem" placeholder="pessoa@gmail.com"><label>Ingresso</label><select id="gtk">${Object.entries(TICKETS).map(([k,v])=>`<option value="${k}">${v.label}</option>`).join("")}</select><button class="btn" onclick="grantEmail()">Liberar</button></div>${users.map(u=>{const a=acc(u.uid)||{status:"none",ticket:"—"};const top=isTop(u.uid);return `<div class="card"><div class="row"><strong>${esc(u.name||u.email)}</strong><span class="pill ${a.status==="active"?"ok":"wait"}">${a.status}</span></div><p class="m">${esc(u.email)} · ${(TICKETS[a.ticket]||{}).label||a.ticket} · ${top?"PLAYER TOP":xp(u.uid)+" pts"}</p><div class="row" style="margin-top:8px"><button class="btn btn3" style="margin:0" onclick="setAcc('${u.uid}','active')">Liberar</button><button class="btn danger" style="margin:0" onclick="setAcc('${u.uid}','blocked')">Bloquear</button></div>${ticketOf(u.uid).kind==="presencial"?consumeBox(u):""}</div>`}).join("")}<div class="card"><h3>Log</h3>${(C.logs||[]).slice(0,8).map(l=>`<p class="m">${esc(l.detail)}</p>`).join("")||"<p class='m'>vazio</p>"}</div>`)}
function consumeBox(u){if(isTop(u.uid))return `<p class="q">PLAYER TOP · liberado.</p><button class="btn btn2" onclick="consume('${u.uid}','refeicao')">Registrar refeição</button>`;return `<p class="q">Padrão · ${used(u.uid,"refeicao")}/${QUOTA.refeicao} refeição · ${used(u.uid,"lanche")}/${QUOTA.lanche} lanche · ${used(u.uid,"bebida")}/${QUOTA.bebida} bebida</p><div class="row"><button class="btn btn3" style="margin:0" onclick="consume('${u.uid}','refeicao')">Refeição</button><button class="btn btn3" style="margin:0" onclick="consume('${u.uid}','lanche')">Lanche</button><button class="btn btn3" style="margin:0" onclick="consume('${u.uid}','bebida')">Bebida</button></div>`}
function consume(uid,item){if(!isTop(uid)&&used(uid,item)>=(QUOTA[item]||1)){toast("Saldo zerado");return}C.cons.push({uid,item,at:iso(),by:me.email});save();log("consumo",user(uid).name+" · "+item);toast("Baixa ok");render()}
function grantEmail(){const email=(document.getElementById("gem").value||"").trim().toLowerCase();const ticket=document.getElementById("gtk").value;if(!email.includes("@")){toast("E-mail");return}const found=Object.values(C.users).find(u=>(u.email||"").toLowerCase()===email);if(!found){const fake="email_"+email.replace(/[^a-z0-9]/g,"_");persistUser({uid:fake,email,name:email,photo:"",createdAt:iso(),lastLogin:"",role:"PARTICIPANTE",onboardingDone:false,public:{}});persistAccess(fake,{status:"active",ticket,ents:TICKETS[ticket].ents,email,at:iso()});tryCloud(()=>db.collection("legado_invites").doc(email).set({email,status:"active",ticket,ents:TICKETS[ticket].ents,at:iso()}));toast("Pré-liberado");render();return}setAcc(found.uid,"active",ticket)}
function setAcc(uid,status,ticket){const prev=acc(uid)||{};const t=ticket||prev.ticket||"presencial";persistAccess(uid,{status,ticket:t,ents:TICKETS[t].ents,email:(user(uid)||{}).email,at:iso()});log("acesso",status+" "+t);toast(status==="active"?"Liberado":"Bloqueado");render()}
function nav(){const items=[["home","\u25cf","Ingresso"],["play","\u2726","Missões"],["live","\u25ce","Vivo"],["people","\u25cb","Gente"],["me","\u25cc","Eu"]];return `<nav class="nav">${items.map(([id,i,l])=>`<button class="${route===id?"on":""}" onclick="go('${id}')"><div>${i}</div>${l}</button>`).join("")}</nav>`}
function shell(html){return `<div class="wrap"><div class="row"><div class="brand">Convergência</div><div class="m">Mini 01</div></div>${html}${nav()}</div>`}
function render(){const el=document.getElementById("app");const map={boot:()=>`<div class="gate"><p class="q">Abrindo…</p></div>`,login:viewLogin,pending:viewPending,onboard:viewOnboard,home:viewHome,play:viewPlay,people:viewPeople,live:viewLive,me:viewMe,staff:viewStaff};el.innerHTML=(map[route]||viewHome)()}
render();
setInterval(()=>{if(route==="home"&&me&&entitled())render()},30000);
